"""make plot number globally unique

Revision ID: 4cb60bf4ba4c
Revises: cd800e2e2c46
Create Date: 2026-09-04 14:17:52.828714
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa




revision: str = '4cb60bf4ba4c'
down_revision: Union[str, Sequence[str], None] = 'cd800e2e2c46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_plots_street_number'), 'plots', type_='unique')
    op.create_unique_constraint('uq_plots_plot_number', 'plots', ['plot_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_plots_plot_number', 'plots', type_='unique')
    op.create_unique_constraint(op.f('uq_plots_street_number'), 'plots', ['street_id', 'plot_number'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
