"""create member plots table

Revision ID: 59856dca4f5e
Revises: 1e06bf0b0eaa
Create Date: 2026-09-04 14:55:05.432644
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa




revision: str = '59856dca4f5e'
down_revision: Union[str, Sequence[str], None] = '1e06bf0b0eaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member_plots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('plot_id', sa.Integer(), nullable=False),
    sa.Column('ownership_share', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['plot_id'], ['plots.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('member_plots')
    # ### end Alembic commands ###
